kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.17.11
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
  - role: worker
    image: kindest/node:v1.17.11
  - role: worker
    image: kindest/node:v1.17.11
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16

# Calico
# kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
# kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true
