helmDefaults:
  wait: true
  timeout: 1000
  # force: true
  # recreatePods: true
environments:
  default:
    values:
      - ../values/default.yaml
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
releases:
  - name: metrics-server
    namespace: kube-system
    chart: stable/metrics-server
    version: "2.11.1"
    values:
      - ../values/metrics-server.yaml
