bases:
  - ../common.yaml
releases:
  - name: prometheus
    namespace: local
    chart: stable/prometheus-operator
    version: "8.13.8"
    values:
      - ../values/prometheus-operator.yaml.gotmpl
  - name: log-operator
    namespace: local
    chart: banzaicloud-stable/logging-operator
    version: "3.2.0"
    values:
      - createCustomResource: false
