bases:
  - ../common.yaml
releases:
  - name: kong
    namespace: local
    chart: kong/kong
    version: "1.5.0"
    values:
      - ../values/kong.yaml.gotmpl

  - name: nginx
    namespace: local
    chart: ingress-nginx/ingress-nginx
    version: "2.3.0"
    installed: false
    values:
      - ../values/ingress.yaml
