helmDefaults:
  wait: true
  timeout: 1000
  # force: true
  # recreatePods: true
  createNamespace: true
  atomic: true
environments:
  default:
    values:
      - ../values/default.yaml
repositories:
  - name: kong
    url: https://charts.konghq.com
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
releases:
  - name: kong
    namespace: local
    chart: kong/kong
    version: "1.5.0"
    values:
      - ../values/kong.yaml.gotmpl

  - name: nginx
    namespace: local
    chart: ingress-nginx/ingress-nginx
    version: "2.3.0"
    installed: false
    values:
      - ../values/ingress.yaml
